name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to main branch
  pull_request:
    branches:
      - main  # Trigger workflow on pull requests to main branch

jobs:
  lint:
    name: Code Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install flake8

      - name: Run Linter
        run: |
          flake8 . --count --show-source --statistics

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: lint  # Ensures linting job passes before this job runs

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Cloud Registry
        env:
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        run: |
          echo "${REGISTRY_PASSWORD}" | docker login -u "${REGISTRY_USERNAME}" --password-stdin 651706738188.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t my-travel-agency-repo .
        
      - name: Tag Docker image
        run: |
          docker tag my-travel-agency-repo:latest 651706738188.dkr.ecr.us-east-1.amazonaws.com/my-travel-agency-repo:latest

      - name: Push Docker image
        run: |
          docker push 651706738188.dkr.ecr.us-east-1.amazonaws.com/my-travel-agency-repo:latest